### ISSUE TITLE
Performance Task

### ISSUE THREAD

**Issue by LucidAPs** [NoChanceSD/PvPManager-Issues#119]
MC 1.15.2
Paper Fork Tuinity
Java 11

72% of the tick is insane!

https://timings.aikar.co/?id=9bbf274c367a4279bff7c147d2b1d8a5#timings

https://i.imgur.com/n1oAKBj.jpg

**Comment by NoChanceSD** [comment]
It's the loading chunks on auto respawn, it's not really the plugin, it's the server respawning the player and it shows up as my plugin since i call the function.
On 1.15 this is a heavier task but luckily you can just disable auto respawn in the config and use the new 1.15 gamerule from mojang: /gamerule doImmediateRespawn true
Should fix it for now, in the next update i will automatically use the new gamerule instead of the previous way for 1.15 servers.

**Comment by NoChanceSD** [comment]
Check the new update when you can, should improve this.

**Comment by NoChanceSD** [comment]
Also, if you're going to make bug reports buy the plugin first, thanks.
